object IntError 
  fn foo(): Int(64) = { 42 }
end IntError